### ISSUE TITLE
I'm confused about the procedure

### ISSUE THREAD

**Issue by phayz** [hferentschik/gollum-openshifted#1]
I began using these instructions in the hope of creating a gollum-powered wiki hosted on OpenShift Flex but am a little confused.

The instructions given the README are as follows:
$ git clone git@github.com:hferentschik/gollum-openshifted.git
$ git remote rm origin
$ rhc-create-domain -n <your-domain> -l <email> -p <password>
$ rhc-create-app -a <app> -t rack-1.1 -l <email> -p <password> --nogit <git-url>
$ git remote add openshift <git-url>  
$ git push -f openshift master
<your-domain> - The domain name you want to use for your apps
<email> - The email you signed up with for OpenShift
<password> - Your OpenShift password
<git-url> - The OpenShift git URL which you receive when creating the app

What I don't understand is, how can I provide the value for <git-url> when later in the instructions it says that this is "The OpenShift git URL which you receive when creating the app". So to the "rhc-create-app" command you need to provide a value which is output by the "rhc-create-app" command!? I'm utterly confused.

On a minor note I'm not sure just what "git remote rm origin" achieves.

Any help/hints would be appreciated.

**Comment by hferentschik** [comment]
Hi,

thanks for the feedback. Let's see if I can clarify your questions.
First off, the instructions are for OpenShift Express. I would assume that you can get it to work on OpenShift Flex as well, but I haven't tried. As far as I know, Openshift Express and Flex use different tool chains to create and manage apps. I will see if I can try against OpenShift Flex as well and add some additional notes. For now it is up to you to match the listed commands to OpenShift Flex.

> What I don't understand is, how can I provide the value for when later in the instructions it says that this is "The 
> OpenShift git URL which you receive when creating the app". So to the "rhc-create-app" command you need to provide > a value which is output by the "rhc-create-app" command!? I'm utterly confused.

Nope. Maybe the formatting was bad. You don't have to specify the <git-url> to the _rhc-create-app_ command. It gets outputted by it. I tried updating the readme. Once you run the command a whole bunch of stuff gets outputted. Somewhere at the bottom will be the git url. This is the url to which to push your code for deployment.

> On a minor note I'm not sure just what "git remote rm origin" achieves.

This is technically not needed, but probably a good idea. If you followed my example you are cloning my repo to your local machine. If you then would edit anything and just write _git push_ you would try to push back into my repo (which would of course not work, but still...). _git push_ is a shortcut for _git push origin master_ and when you clone a git repo, git will configure a remote called _origin_ pointing to the original repo. By executing _git remote rm origin_ you basically cut the link to my repository. If you want to be able to do _git push_ to your OpenShift app you have to run

```
git remote rm origin
git remote add origin <git-url>
```

Hope this helps.
